- src/pages/containers/activities/index.mdx
Removed second multi-stage build and used it as default. This also removes the maven dependency on the client side.
> Using multi-stage dockerfile as default build.

- src/pages/kubernetes/activities/labs/lab3/index.mdx
> Minor wording issue

- src/pages/prerequisites/index.mdx
Some formatting updates in this tab view.
> Formatting Fixes - Prereqs OCP4

- src/pages/kubernetes/activities/labs/lab7/index.mdx
every minute vs. every second minute
> Small typo on cron job description

- src/pages/containers/activities/index.mdx
- Java is not required to be install on students computer, so remove the instructions.
- Some place holders missing `<command>`
> update docker lab

- src/data/nav-items.yaml
- src/pages/activities/index.mdx
- src/pages/eda/activities/labs/lab1/index.mdx
- src/pages/eda/activities/labs/lab1/solution.mdx
- src/pages/eda/activities/labs/lab2/index.mdx
- src/pages/eda/activities/labs/lab2/solution.mdx
- src/pages/eda/activities/labs/lab3/index.mdx
- src/pages/eda/activities/labs/lab3/solution.mdx
- src/pages/eda/activities/labs/lab4/index.mdx
- src/pages/eda/index.mdx
Signed-off-by: Rick Osowski <rosowski@gmail.com>
> Initial EDA pass

- src/data/nav-items.yaml
- src/pages/monitoring/sysdig/activities/minikube/index.md
- src/pages/monitoring/sysdig/index.mdx
Add content for Monitoring specific to IBM Cloud Sysdig
> Sysdig monitoring

- src/pages/monitoring/sysdig/activities/prometheus/java.mdx
- src/pages/monitoring/sysdig/activities/prometheus/nodejs.mdx
> update links to github for prometheus examples

- src/pages/activities/index.mdx
- src/pages/eda/index.mdx
> fix broken links for monitoring and update eda with video

- src/pages/containers/index.mdx
> add commands used during live demo for containers

- src/pages/activities/index.mdx
- src/pages/kubernetes/activities/labs/ingress-iks/index.mdx
- src/pages/kubernetes/services-networking/index.mdx
- static/yamls/ingress-controller/iks-ingress-v1.7.1.yaml
> lab free iks cluster ingress controller

- src/pages/eda/activities/labs/lab1/index.mdx
Signed-off-by: Rick Osowski <rosowski@gmail.com>
> Updated eda-lab1-nodejs docker instructions

- src/pages/data-services/activities/labs/lab1/index.mdx
- static/yamls/postgresql/clouddb-deployment.yaml
> minor updates to postgresql lab

- src/pages/containers/activities/index.mdx
- src/pages/containers/activities/solution/index.mdx
double check the link is not broken but it downloads a file, I changed it to load a index html with the answers.
> fix broken link to docker lab solution

- src/pages/continuous-integration/activities/ibm-toolchain/index.mdx
> update to tekton lab on ibmcloud

- src/pages/kubernetes/state-persistence/index.mdx
- src/pages/kubernetes/troubleshooting/index.mdx
> update pvc and debug lectures

- src/pages/kubernetes/observability/index.mdx
> remove startup prodbe

- src/pages/data-services/activities/labs/lab1/index.mdx
> update postgresql db

- src/pages/monitoring/sysdig/activities/prometheus/java.mdx
- src/pages/monitoring/sysdig/activities/prometheus/nodejs.mdx
> update ports for minitoring labs

- src/pages/monitoring/sysdig/activities/minikube/index.mdx
https://twitter.com/csantanapr/status/1284126119386648577?s=20 (In response to this)(
> updated from LOGDNA to Sysdig in the steps

- src/pages/course-overview/index.mdx
- src/pages/news/index.mdx
> fix broken links
